[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CliqueTrees = "60701a23-6482-424a-84db-faee86b9b1f8"
CryptoMiniSat_jll = "cf02a7a8-8cd0-5932-97be-477f95a4d9ce"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
TreeWidthSolver = "7d267fc5-9ace-409f-a54c-cd2374872a55"

[sources]
CliqueTrees = {path = ".."}
