name = "CliqueTrees"
uuid = "60701a23-6482-424a-84db-faee86b9b1f8"
license = "MIT"
authors = ["Richard Samuelson <rsamuelson@ufl.edu>"]
version = "0.4.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
AMD = "14f7f29c-3bd6-536c-9a0b-7339e30b5a3e"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
Laplacians = "6f8e5838-0efe-5de0-80a3-5fb4f8dbb1de"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
TreeWidthSolver = "7d267fc5-9ace-409f-a54c-cd2374872a55"

[extensions]
AMDExt = "AMD"
CatlabExt = "Catlab"
LaplaciansExt = "Laplacians"
MetisExt = "Metis"
TreeWidthSolverExt = "TreeWidthSolver"

[compat]
AMD = "0.5"
AbstractTrees = "0.4"
ArgCheck = "2.4.0"
Catlab = "0.16"
DataStructures = "0.17, 0.18"
Graphs = "1"
Laplacians = "1.1"
LinearAlgebra = "1"
Metis = "1"
SparseArrays = "1"
TreeWidthSolver = "0.3"
julia = "1.8"

[extras]
AMD = "14f7f29c-3bd6-536c-9a0b-7339e30b5a3e"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
Laplacians = "6f8e5838-0efe-5de0-80a3-5fb4f8dbb1de"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
TreeWidthSolver = "7d267fc5-9ace-409f-a54c-cd2374872a55"
