name = "CliqueTrees"
uuid = "60701a23-6482-424a-84db-faee86b9b1f8"
license = "MIT"
authors = ["Richard Samuelson <rsamuelson@ufl.edu>"]
version = "1.7.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
AMD = "14f7f29c-3bd6-536c-9a0b-7339e30b5a3e"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
CryptoMiniSat_jll = "cf02a7a8-8cd0-5932-97be-477f95a4d9ce"
FlowCutterPACE17_jll = "008204e2-cd5c-5c6d-9360-d31f32b5f6c2"
KaHyPar = "2a6221f6-aa48-11e9-3542-2d9e0ef01880"
Laplacians = "6f8e5838-0efe-5de0-80a3-5fb4f8dbb1de"
Lingeling_jll = "54ea7443-b7cf-5485-b0d0-86c7d7a308e1"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
PicoSAT_jll = "e78fa76d-a187-569f-aede-ad11521a2edf"
TreeWidthSolver = "7d267fc5-9ace-409f-a54c-cd2374872a55"
libpicosat_jll = "6b231c3b-13f8-5ced-86ae-8860c7f75d86"

[extensions]
AMDExt = "AMD"
CatlabExt = "Catlab"
CryptoMiniSat_jllExt = "CryptoMiniSat_jll"
FlowCutterPACE17_jllExt = "FlowCutterPACE17_jll"
KaHyParExt = "KaHyPar"
LaplaciansExt = "Laplacians"
Lingeling_jllExt = "Lingeling_jll"
MetisExt = "Metis"
PicoSAT_jllExt = "PicoSAT_jll"
TreeWidthSolverExt = "TreeWidthSolver"
libpicosat_jllExt = "libpicosat_jll"

[compat]
AMD = "0.5"
AbstractTrees = "0.4"
ArgCheck = "2.4.0"
Catlab = "0.16"
CryptoMiniSat_jll = "5"
FlowCutterPACE17_jll = "0.0.2"
Graphs = "1"
KaHyPar = "0.3"
Laplacians = "1.1"
LinearAlgebra = "1"
Lingeling_jll = "1"
Metis = "1"
PicoSAT_jll = "965"
SparseArrays = "1"
TreeWidthSolver = "0.3"
julia = "1.8"
libpicosat_jll = "965"

[extras]
AMD = "14f7f29c-3bd6-536c-9a0b-7339e30b5a3e"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
CryptoMiniSat_jll = "cf02a7a8-8cd0-5932-97be-477f95a4d9ce"
FlowCutterPACE17_jll = "008204e2-cd5c-5c6d-9360-d31f32b5f6c2"
KaHyPar = "2a6221f6-aa48-11e9-3542-2d9e0ef01880"
Laplacians = "6f8e5838-0efe-5de0-80a3-5fb4f8dbb1de"
Lingeling_jll = "54ea7443-b7cf-5485-b0d0-86c7d7a308e1"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
PicoSAT_jll = "e78fa76d-a187-569f-aede-ad11521a2edf"
TreeWidthSolver = "7d267fc5-9ace-409f-a54c-cd2374872a55"
libpicosat_jll = "6b231c3b-13f8-5ced-86ae-8860c7f75d86"
