name = "CliqueTrees"
uuid = "60701a23-6482-424a-84db-faee86b9b1f8"
license = "MIT"
version = "1.12.3"
authors = ["Richard Samuelson <rsamuelson@ufl.edu>"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
FixedSizeArrays = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
AMD = "14f7f29c-3bd6-536c-9a0b-7339e30b5a3e"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
FlowCutterPACE17_jll = "008204e2-cd5c-5c6d-9360-d31f32b5f6c2"
KaHyPar = "2a6221f6-aa48-11e9-3542-2d9e0ef01880"
Laplacians = "6f8e5838-0efe-5de0-80a3-5fb4f8dbb1de"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
TreeWidthSolver = "7d267fc5-9ace-409f-a54c-cd2374872a55"

[extensions]
AMDExt = "AMD"
CatlabExt = "Catlab"
FlowCutterPACE17_jllExt = "FlowCutterPACE17_jll"
KaHyParExt = "KaHyPar"
LaplaciansExt = "Laplacians"
MetisExt = "Metis"
TreeWidthSolverExt = "TreeWidthSolver"

[compat]
AMD = "0.5"
AbstractTrees = "0.4"
Catlab = "0.16, 0.17"
FillArrays = "1"
FixedSizeArrays = "1"
FlowCutterPACE17_jll = "0.0.2"
Graphs = "1"
KaHyPar = "0.3"
Laplacians = "1.1"
LinearAlgebra = "1"
Metis = "1"
Random = "1"
SparseArrays = "1"
TreeWidthSolver = "0.3"
julia = "1.8"

[extras]
AMD = "14f7f29c-3bd6-536c-9a0b-7339e30b5a3e"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
FlowCutterPACE17_jll = "008204e2-cd5c-5c6d-9360-d31f32b5f6c2"
KaHyPar = "2a6221f6-aa48-11e9-3542-2d9e0ef01880"
Laplacians = "6f8e5838-0efe-5de0-80a3-5fb4f8dbb1de"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
TreeWidthSolver = "7d267fc5-9ace-409f-a54c-cd2374872a55"
