name = "Multifrontal"
uuid = "f5d7b34c-5a5e-4a5c-9a6a-3c8f5a5b4e6d"
license = "MIT"
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
CliqueTrees = "60701a23-6482-424a-84db-faee86b9b1f8"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
AbstractTrees = "0.4.5"
CliqueTrees = "1.12"
Graphs = "1.13.4"
julia = "1.10"
